networks:
  sitea_net: {}
  siteb_net: {}

volumes:
  sitea_mongo_data:
  siteb_mongo_data:

services:
  ############### SITE A ###############
  sitea_mongo:
    image: mongo:6
    volumes: [ sitea_mongo_data:/data/db ]
    networks: [ sitea_net ]

  sitea_rock:
    image: datashield/rock-base:latest
    environment:
      ROCK_ADMINISTRATOR_PASSWORD: ${SITEA_ROCK_ADMIN_PWD}
    networks: [ sitea_net ]

  sitea_opal:
    image: obiba/opal:latest
    depends_on: [ sitea_mongo, sitea_rock ]
    ports: [ "${OPAL_PORT_A}:8080" ]
    environment:
      MONGO_HOST: sitea_mongo
      MONGO_PORT: 27017
      ROCK_HOSTS: sitea_rock:8085
      OPAL_ADMINISTRATOR_PASSWORD: ${SITEA_OPAL_ADMIN_PWD}
    volumes:
      - "${PROJECT_HOME}/sitea/opal_home:/srv"
    networks: [ sitea_net ]

  ############### SITE B ###############
  siteb_mongo:
    image: mongo:6
    volumes: [ siteb_mongo_data:/data/db ]
    networks: [ siteb_net ]

  siteb_rock:
    image: datashield/rock-base:latest
    environment:
      OPAL_ADMINISTRATOR_PASSWORD: ${SITEB_ROCK_ADMIN_PWD}
    networks: [ siteb_net ]

  siteb_opal:
    image: obiba/opal:latest
    depends_on: [ siteb_mongo, siteb_rock ]
    ports: [ "${OPAL_PORT_B}:8080" ]
    environment:
      MONGO_HOST: siteb_mongo
      MONGO_PORT: 27017
      ROCK_HOSTS: siteb_rock:8085
      OPAL_ADMINISTRATOR_PASSWORD: ${SITEB_OPAL_ADMIN_PWD}
    volumes:
      - "${PROJECT_HOME}/siteb/opal_home:/srv"
    networks: [ siteb_net ]

  ############### CLIENT ###############
  ds_client:
    image: rocker/verse:latest
    ports: [ "${RSTUDIO_PORT}:8787" ]
    environment:
      PASSWORD: ${CLIENT_VERSE_RSTUDIO_PWD}
    networks: [ sitea_net, siteb_net ]
