networks:
  sitea_net:
    driver: bridge
    labels:
      - "opal-lab.network=sitea"
  siteb_net:
    driver: bridge
    labels:
      - "opal-lab.network=siteb"

volumes:
  sitea_mongo_data:
    labels:
      - "opal-lab.volume=sitea-mongo"
  siteb_mongo_data:
    labels:
      - "opal-lab.volume=siteb-mongo"

services:
  ############### SITE A ###############
  sitea_mongo:
    image: mongo:6
    container_name: opal-lab-sitea-mongo
    restart: unless-stopped
    volumes:
      - sitea_mongo_data:/data/db
    networks:
      - sitea_net
    labels:
      - "opal-lab.service=database"
      - "opal-lab.site=sitea"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  sitea_rock:
    image: datashield/rock-base:latest
    container_name: opal-lab-sitea-rock
    restart: unless-stopped
    environment:
      ROCK_ADMINISTRATOR_PASSWORD: ${SITEA_ROCK_ADMIN_PWD}
      ROCK_USER_NAME: ${SITEA_ROCK_USER_NAME}
      ROCK_USER_PASSWORD: ${SITEA_ROCK_USER_PWD}
      ROCK_ID: sitea-rock
      ROCK_CLUSTER: default
    networks:
      - sitea_net
    labels:
      - "opal-lab.service=rock"
      - "opal-lab.site=sitea"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  sitea_opal:
    image: obiba/opal:latest
    container_name: opal-lab-sitea-opal
    restart: unless-stopped
    depends_on:
      sitea_mongo:
        condition: service_healthy
      sitea_rock:
        condition: service_healthy
    ports:
      - "${OPAL_PORT_A:-18880}:8080"
      - "${OPAL_HTTPS_PORT_A:-18443}:8443"
    environment:
      MONGO_HOST: sitea_mongo
      MONGO_PORT: 27017
      ROCK_HOSTS: sitea_rock:8085
      APPS_DISCOVERY_ROCK_HOSTS: sitea_rock:8085
      OPAL_ADMINISTRATOR_PASSWORD: ${SITEA_OPAL_ADMIN_PWD}
      ROCK_ADMINISTRATOR_USER: administrator
      ROCK_ADMINISTRATOR_PASSWORD: ${SITEA_ROCK_ADMIN_PWD}
      # Manager credentials are optional; manager role is not used in this demo
      ROCK_MANAGER_USER: manager
      ROCK_MANAGER_PASSWORD: ${SITEA_ROCK_ADMIN_PWD}
      # Regular Rock user credentials used for DataSHIELD operations
      ROCK_USER_USER: ${SITEA_ROCK_USER_NAME}
      ROCK_USER_PASSWORD: ${SITEA_ROCK_USER_PWD}
      JAVA_OPTS: "-Xmx2g"
      # Configurazione SSL condizionale
      OPAL_HTTPS_PORT: 8443
      OPAL_SSL_KEYSTORE_FILE: /srv/ssl/sitea-keystore.p12
      OPAL_SSL_KEYSTORE_PASSWORD: ${SSL_KEYSTORE_PASSWORD}
      OPAL_SSL_KEYSTORE_TYPE: PKCS12
      # NON forza HTTPS - permette anche HTTP per backward compatibility
      OPAL_HTTPS_ONLY: ${OPAL_FORCE_HTTPS:-false}
    volumes:
      - "${PROJECT_HOME}/sitea/opal_home:/srv"
      - "${PROJECT_HOME}/ssl:/srv/ssl"
    networks:
      - sitea_net
    labels:
      - "opal-lab.service=opal"
      - "opal-lab.site=sitea"
    healthcheck:
      # Controlla prima HTTPS, poi HTTP come fallback
      test: ["CMD", "sh", "-c", "curl -f -k https://localhost:8443/ || curl -f http://localhost:8080/"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 120s

  ############### SITE B ###############
  siteb_mongo:
    image: mongo:6
    container_name: opal-lab-siteb-mongo
    restart: unless-stopped
    volumes:
      - siteb_mongo_data:/data/db
    networks:
      - siteb_net
    labels:
      - "opal-lab.service=database"
      - "opal-lab.site=siteb"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  siteb_rock:
    image: datashield/rock-base:latest
    container_name: opal-lab-siteb-rock
    restart: unless-stopped
    environment:
      ROCK_ADMINISTRATOR_PASSWORD: ${SITEB_ROCK_ADMIN_PWD}
      ROCK_USER_NAME: ${SITEB_ROCK_USER_NAME}
      ROCK_USER_PASSWORD: ${SITEB_ROCK_USER_PWD}
      ROCK_ID: siteb-rock
      ROCK_CLUSTER: default
    networks:
      - siteb_net
    labels:
      - "opal-lab.service=rock"
      - "opal-lab.site=siteb"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  siteb_opal:
    image: obiba/opal:latest
    container_name: opal-lab-siteb-opal
    restart: unless-stopped
    depends_on:
      siteb_mongo:
        condition: service_healthy
      siteb_rock:
        condition: service_healthy
    ports:
      - "${OPAL_PORT_B:-28880}:8080"
      - "${OPAL_HTTPS_PORT_B:-28443}:8443"
    environment:
      MONGO_HOST: siteb_mongo
      MONGO_PORT: 27017
      ROCK_HOSTS: siteb_rock:8085
      APPS_DISCOVERY_ROCK_HOSTS: siteb_rock:8085
      OPAL_ADMINISTRATOR_PASSWORD: ${SITEB_OPAL_ADMIN_PWD}
      ROCK_ADMINISTRATOR_USER: administrator
      ROCK_ADMINISTRATOR_PASSWORD: ${SITEB_ROCK_ADMIN_PWD}
      # Manager credentials are optional; manager role is not used in this demo
      ROCK_MANAGER_USER: manager
      ROCK_MANAGER_PASSWORD: ${SITEB_ROCK_ADMIN_PWD}
      # Regular Rock user credentials used for DataSHIELD operations
      ROCK_USER_USER: ${SITEB_ROCK_USER_NAME}
      ROCK_USER_PASSWORD: ${SITEB_ROCK_USER_PWD}
      JAVA_OPTS: "-Xmx2g"
      OPAL_HTTPS_PORT: 8443
      OPAL_SSL_KEYSTORE_FILE: /srv/ssl/siteb-keystore.p12
      OPAL_SSL_KEYSTORE_PASSWORD: ${SSL_KEYSTORE_PASSWORD}
      OPAL_SSL_KEYSTORE_TYPE: PKCS12
      OPAL_HTTPS_ONLY: ${OPAL_FORCE_HTTPS:-false}
    volumes:
      - "${PROJECT_HOME}/siteb/opal_home:/srv"
      - "${PROJECT_HOME}/ssl:/srv/ssl"
    networks:
      - siteb_net
    labels:
      - "opal-lab.service=opal"
      - "opal-lab.site=siteb"
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f -k https://localhost:8443/ || curl -f http://localhost:8080/"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 120s
